# The reason for blocking Google Search is that sometimes I can't stop searching for the mature websites in there endlessly.
# It goes without saying that not being able to use it is inconvenient, but I've realized I haven't been using it that much.
# That's why it's not a bad idea that it's prohibited normally and able to be unlocked whenever I would like to utilize it.
# The name origin of this network restriction comes from: https://chatgpt.com/share/6a896657-07ac-83e9-a0df-64d4560f2db6
address=/www.google.com/
address=/www.google.co.jp/



# These domains are used in YouTube Ads thumbnails (shown in the list of the recommended videos in the video play page)
# and they sometimes include a little bit sexual pictures. Google services like Google Meet, Google Drive, Gmail etc.
# also use lh3.googleusercontent.com, even though it's not always necessary (mainly the images and the icons used within
# those services)
# https://knowledge.workspace.google.com/admin/meet/prepare-your-network-for-meet-meetings-and-live-streams
address=/lh1.googleusercontent.com/
address=/lh2.googleusercontent.com/
address=/lh3.googleusercontent.com/
address=/lh4.googleusercontent.com/
address=/lh5.googleusercontent.com/
address=/lh6.googleusercontent.com/
address=/lh7.googleusercontent.com/
address=/lh8.googleusercontent.com/
address=/lh9.googleusercontent.com/
address=/ci3.googleusercontent.com/ # The images in Gmail



# See athena_allow.conf for details
address=/accounts.youtube.com/
address=/studio.youtube.com/rtmp.youtube.com/c.youtube.com/i9.ytimg.com/yt3.ggpht.com/
address=/upload.youtube.com/
