# The reason for blocking Google Search is that sometimes I can't stop searching for the mature websites in there endlessly.
# It goes without saying that not being able to use it is inconvenient, but I've realized I haven't been using it that much.
# That's why it's not a bad idea that it's prohibited normally and able to be unlocked whenever I would like to utilize it.
# The name origin of this network restriction comes from: https://chatgpt.com/share/6a896657-07ac-83e9-a0df-64d4560f2db6
address=/www.google.com/
address=/www.google.co.jp/
