# A video can't be uploaded unless 'www.google.com' is available, and the domains below are also needed. 'www.google.com'
# is blocked by athena.conf and these are restricted by youtube.conf. Allowing these and blocking YouTube itself at the
# same time is possible, but allowing these all the time is confusing, because when only these are allowed, YouTube Studio
# itself is available as an interface, so it's difficult to notice why posting a video fails. It is designed to unlock
# athena.conf and athena_allow.conf at the same time, which means uploading a video is not allowed all the time. So you
# have to unlock them first when you'd like to upload a video to YouTube. It might feel like it's a little bit of a hassle,
# but it's designed like that on purpose to avoid confusion.



# Allow YouTube Account (YouTube account authorization domain)
server=/accounts.youtube.com/#

# Allow YouTube Live streaming
#
#   studio.youtube.com: YouTube live stream page
#   rtmp.youtube.com:   YouTube live stream
#   c.youtube.com:      YouTube live stream preview
#   i9.ytimg.com:       YouTube thumbnails
#   yt3.ggpht.com:      YouTube icons
#
server=/studio.youtube.com/rtmp.youtube.com/c.youtube.com/i9.ytimg.com/yt3.ggpht.com/#

# Allow YouTube video uploading
server=/upload.youtube.com/#
