# Related services: chime.conf, knock.conf, siren.conf, social_media.conf, social_media_allow.conf

# whimsical, purposeless sites used only to check whether network restrictions are working as expected
# server=/theuselessweb.com/longdogechallenge.com/cat-bounce.com/pointerpointer.com/zzz.zoomquilt.org/#

# basically opposite of chime.conf (see chime.conf about remarks or notes)
#
server=/gmail.com/mail.google.com/inbox.google.com/#
server=/line.me/linecorp.com/line-apps.com/line-scdn.net/line.naver.jp/#
server=/discord.com/#
server=/chatwork.com/#
server=/mercari.com/mercari.jp/#
