# Blocking these services unless the task is accomplished is a bit over the top...
# address=/ted.com/tedcdn.com/
# address=/dotinstall.com/
# address=/daigovideolab.jp/
# address=/yuchrszk.blogspot.com/

# These might be unnecessary because they're not so stimulating...?
address=/quizknock.com/
address=/sizu.me/

# These are basically the same as amazon.conf, but the schedule and the restrictions are different.
address=/amazon.co.jp/
address=/wikipedia.org/
address=/dic.pixiv.net/
address=/dic.nicovideo.jp/
address=/news.nicovideo.jp/niconiconews.jp/originalnews.nico/
address=/info.nicomanga.jp/
address=/commons.nicovideo.jp/
address=/commons.wikimedia.org/
address=/note.com/

# hatena.com
#
# Most of the subdomains are redirected to hatena.ne.jp (e.g. m.hatena.com -> m.hatena.ne.jp,) but not all of them are
# (e.g. s.hatena.com.) hatena.com seems to be hardly ever used in Japan, so it's blocked at the apex domain level to
# avoid unwanted access.
#
# https://hatena.co.jp/press/release/entry/2007/07/11/193714
#
address=/hatena.com/

# hatena.ne.jp
#
# Hatena owns a lot of small services and uses the hatena.ne.jp subdomains, and most of them are not used very often
# unless you are a power user, so they are blocked at the apex domain level to make it easy to maintain their domains.
#
# https://hatena.co.jp/press/release/entry/2006/03/13/181912
#
address=/hatena.ne.jp/
# address=/a.hatena.ne.jp/
# address=/b.hatena.ne.jp/        # also in ometeotl.conf
# address=/blog.hatena.ne.jp/
# address=/counter.hatena.ne.jp/
# address=/d.hatena.ne.jp/
# address=/f.hatena.ne.jp/
# address=/g.hatena.ne.jp/
# address=/graph.hatena.ne.jp/
# address=/i.hatena.ne.jp/
# address=/m.hatena.ne.jp/
# address=/map.hatena.ne.jp/
# address=/p.hatena.ne.jp/
# address=/q.hatena.ne.jp/
# address=/r.hatena.ne.jp/
# address=/ring.hatena.ne.jp/
# address=/s.hatena.ne.jp/
# address=/search.hatena.ne.jp/
# address=/www.hatena.ne.jp/      # hatena.ne.jp -> www.hatena.ne.jp

# Hatena Blog
#
# https://share.google/aimode/JXN7XXdNzN2rYsD4P
# https://staff.hatenablog.com/entry/2018/02/22/150000
#
address=/hatena.blog/
address=/hatenablog.com/
address=/hatenablog.jp/
address=/hateblo.jp/
address=/hatenadiary.com/
address=/hatenadiary.jp/

# Hatena Blog images
address=/cdn-ak.f.st-hatena.com/
address=/cdn.blog.st-hatena.com/
address=/cdn.image.st-hatena.com/
address=/cdn.profile-image.st-hatena.com/

# Hatelabo
#
# Some of the services (like anond.hatelabo.jp) are toxic, and Hatelabo seems to produce and close a lot, so it is easy
# to block it at the apex domain level.
#
# https://hatena.co.jp/information/product
#
address=/hatelabo.jp/
