# TODO:
#   This file has been created to restrict only the thumbnails and/or the previews of Netflix content (if possible)
#   without blocking Netflix itself. But the resources haven't been investigated because I haven't watched Netflix for a
#   while. Do some research on the resources and apply them (if possible) if I contract Netflix again in the future.
