# Deny Niconico Douga
#
#   source:
#     investigated on my own
#   also blocked by:
#     superman_upstream.conf (AdGuard DNS Family Protection)
#   free:
#     yes (content itself)
#

# nicovideo.jp
address=/astral.nicovideo.jp/
address=/user-follow-api.nicovideo.jp/
address=/mute-api.nicovideo.jp/
address=/nvapi.nicovideo.jp/
address=/nvcomment.nicovideo.jp/
address=/log.recommend.nicovideo.jp/
address=/api.nicoad.nicovideo.jp/
address=/ads.nicovideo.jp/
address=/public-api.commons.nicovideo.jp/
address=/wktk.nicovideo.jp/
address=/asset.domand.nicovideo.jp/
address=/delivery.domand.nicovideo.jp/
# not necessary
# address=/a.live2.nicovideo.jp/
# address=/api.dic.nicovideo.jp/
# address=/api.feed.nicovideo.jp/
# address=/api.oshirasebox.nicovideo.jp/
# address=/audition.nicovideo.jp/
# address=/blog.nicovideo.jp/
# address=/dcdn.cdn.nicovideo.jp/
# address=/eapi.beta.hiroba.nicovideo.jp/
# address=/ext.live.nicovideo.jp/
# address=/listing-thumbnail.live.nicovideo.jp/
# address=/live2.nicovideo.jp/
# address=/livedelivery.dlive.nicovideo.jp/
# address=/mjk.nicovideo.jp/
# address=/mpn.live.nicovideo.jp/
# address=/nicovideo.jp/
# address=/nvl.video.nicovideo.jp/
# address=/personalframe.nicovideo.jp/
# address=/public-api.ch.nicovideo.jp/
# address=/public.nvcomment.nicovideo.jp/
# address=/res.ads.nicovideo.jp/
# address=/www.nicovideo.jp/

# nimg.jp
address=/secure-dcdn.cdn.nimg.jp/
address=/nicovideo.cdn.nimg.jp/
address=/nicolive.cdn.nimg.jp/
# not necessary
# address=/assets.embed.res.nimg.jp/
# address=/common-header.nimg.jp/
# address=/dcdn.cdn.nimg.jp/
# address=/img.cdn.nimg.jp/
# address=/img.nicoprofile.nimg.jp/
# address=/ir.cdn.nimg.jp/
# address=/news-img.cdn.nimg.jp/
# address=/resource.video.nimg.jp/
# address=/wktk.nimg.jp/

# other
address=/dmc.nico/
