# NOTE:
#   Both the resources of the videos and their previews are delivered from 'asset.domand.nicovideo.jp', which means it's
#   impossible to filter only the previews of the videos.

address=/img.cdn.nimg.jp/          # the thumbnails of the search or tag results
address=/nicovideo.cdn.nimg.jp/    # the thumbnails of the video top, recommended, history, etc. page
# address=/resource.video.nimg.jp/ # the thumbnails of the playlists, but also includes the main css
address=/img.nicoprofile.nimg.jp/  # the user icons
