# Deny Niconico Douga
#
#   source:
#     investigated on my own
#   also blocked by:
#     superman_upstream.conf (AdGuard DNS Family Protection)
#   free:
#     yes (content itself)
#
address=/astral.nicovideo.jp/
address=/user-follow-api.nicovideo.jp/
address=/mute-api.nicovideo.jp/
address=/nvapi.nicovideo.jp/
address=/nvcomment.nicovideo.jp/
address=/log.recommend.nicovideo.jp/
address=/api.nicoad.nicovideo.jp/
address=/ads.nicovideo.jp/
address=/public-api.commons.nicovideo.jp/
address=/wktk.nicovideo.jp/
address=/secure-dcdn.cdn.nimg.jp/
address=/dmc.nico/
address=/nicovideo.cdn.nimg.jp/
address=/nicolive.cdn.nimg.jp/
